config/routes.rb
Rbliki::Application.routes.draw do
  
  resources :blogs

  root to:  'Blogs#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  
  def index
  	@blogs = Blog.all
  end

  def new
  	@blog = Blog.new
  end

  def create
  	@blog = Blog.create params[:blog]
  	redirect_to blogs_path , notice: "Blog was created successfully"
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    blog = Blog.find params[:id]

    if blog.update_attributes params[:blog]
        redirect_to blogs_path, notice: "Blog was updated successfully."
    end
  end

  def destroy
    Blog.destroy params[:id]
    redirect_to blogs_path, notice: "Blog has been deleted"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<table>
	<%= form_for @blog do |b| %>
		<tr>
			<td>
				<%= b.label :title %> 
			</td>
			<td>
				<%= b.text_field :title %>
			</td>
		</tr>
		<tr>
		<td>
			<%= b.label :description %> 
		</td>
		<td>
			<%= b.text_field :description %>
		</td>
		</tr>
		<tr>
			<td> <%= b.submit %> </td>
		</tr>	
	<% end %>
</table>

app/views/blogs/edit.html.erb
<h2> Edit a Blog </h2>
<%= render 'form' %>

app/views/blogs/index.html.erb
<h2>Blogs</h2>
<table>	
	<% for blog in @blogs %>
	<tr>
		<td>
			<%= blog.title %> | <%= link_to 'Edit', edit_blog_path(blog) %> | <%= link_to 'Delete',blog_path(blog), method: :delete, confirm: "Are you sure ?"  %>
		</td>
	</tr>
	<tr>	
		<td>
			<%= blog.description %>
		</td>
	</tr>
	<% end %>
<tr>
	<td> <%= link_to 'Create Blog', new_blog_path %> </td>
</tr>
</table>

app/views/blogs/new.html.erb
<h2> New Blog </h2>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rbliki</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:notice] -%>
  <p class='notice'><%=h flash[:notice] %></p>
<% end -%>
<%= yield %>

</body>
</html>